In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
admissions = pd.read_csv("admissions_clean.csv")
doctors = pd.read_csv("doctors_preprocessed.csv")
departments = pd.read_csv("departments_clean.csv")

In [4]:
admissions_count = (
    admissions.groupby("Department_ID")["Admission_ID"]
    .count()
    .reset_index(name="Admissions")
)
admissions_count.head()

  Department_ID  Admissions
0          D001         233
1          D002         200
2          D003         320
3          D004         277
4          D005         331

In [5]:
doctors_count = (
    doctors.groupby("Department_ID")["Doctor_ID"]
    .count()
    .reset_index(name="Doctors")
)
doctors_count.head()

  Department_ID  Doctors
0          D001       23
1          D002       20
2          D003       30
3          D004       27
4          D005       33

In [6]:
dept_util = (
    admissions_count.merge(doctors_count, on="Department_ID")
    .merge(departments, left_on="Department_ID", right_on="department_id")
)

dept_util["Patients_per_Doctor"] = dept_util["Admissions"] / dept_util["Doctors"]

def classify(row):
    if row["Patients_per_Doctor"] > 20:
        return "Overloaded"
    elif row["Patients_per_Doctor"] < 5:
        return "Underutilized"
    else:
        return "Balanced"

dept_util["Status"] = dept_util.apply(classify, axis=1)
dept_util

,Department_ID,Admissions,Doctors,department_id,department_name,Patients_per_Doctor,Status
0,D001,233,23,D001,Cardiology,10.130435,Balanced
1,D002,200,20,D002,Neurology,10.000000,Balanced
2,D003,320,30,D003,Orthopedics,10.666667,Balanced
3,D004,277,27,D004,Pediatrics,10.259259,Balanced
4,D005,331,33,D005,Oncology,10.030303,Balanced
5,D006,215,21,D006,ENT,10.238095,Balanced
6,D007,179,20,D007,Dermatology,8.950000,Balanced
7,D008,175,18,D008,General Surgery,9.722222,Balanced
8,D009,169,17,D009,Urology,9.941176,Balanced
9,D010,218,22,D010,Nephrology,9.909091,Balanced
10,D011,159,17,D011,Gynecology,9.352941,Balanced
11,D012,253,27,D012,Psychiatry,9.370370,Balanced
12,D013,317,29,D013,Pulmonology,10.931034,Balanced
13,D014,260,27,D014,Gastroenterology,9.629630,Balanced
14,D015,335,34,D015,Emergency,9.852941,Balanced
15,D016,266,27,D016,Radiology,9.851852,Balanced
16,D017,253,25,D017,ICU,10.120000,Balanced
17,D018,268,27,D018,Ophthalmology,9.925926,Balanced
18,D019,319,32,D019,Endocrinology,9.968750,Balanced
19,D020,253,24,D020,Dental,10.541667,Balanced

In [ ]:
dept_util.to_csv("department_resource_utilization.csv", index=False)